const people=['小夏','林一','陈可','周舟'];
const today=()=>new Date().toLocaleDateString('sv-SE');
const seed=()=>({bills:[{id:1,title:'9 月房租',amount:480000,payer:'林一',members:[...people],date:today(),paid:[]},{id:2,title:'水电燃气费',amount:28660,payer:'小夏',members:[...people],date:today(),paid:['陈可']},{id:3,title:'公共用品采购',amount:8960,payer:'陈可',members:[...people],date:today(),paid:[]}],tasks:[{id:11,title:'客厅清洁',person:'小夏',date:today(),done:false},{id:12,title:'厨房台面与灶台',person:'林一',date:today(),done:false},{id:13,title:'卫生间清洁',person:'陈可',date:today(),done:true},{id:14,title:'倒垃圾 & 更换垃圾袋',person:'周舟',date:today(),done:false}],items:[{id:21,title:'抽纸',qty:2,unit:'包',threshold:2},{id:22,title:'洗洁精',qty:1,unit:'瓶',threshold:1},{id:23,title:'垃圾袋',qty:6,unit:'卷',threshold:2}],rules:[{id:31,title:'安静时间，彼此留一点空间',body:'工作日 23:00 后、周末 24:00 后，公共区域保持安静。打电话或看视频请使用耳机。',signed:['林一','陈可','周舟']},{id:32,title:'公共空间，用完恢复原样',body:'厨房使用后及时清理台面与餐具；个人物品不长期占用客厅。值日当天不方便，可提前和室友协商换班。',signed:[...people]},{id:33,title:'账目透明，分摊有据',body:'公共支出先沟通，付款后及时记账并说明用途。账单确认无误后，尽量在三天内结清。',signed:['林一','陈可']}],user:'小夏'});
let state;try{state=JSON.parse(localStorage.getItem('roommate-v1'))||seed()}catch{state=seed()}let page='home',filter='all';
const $=s=>document.querySelector(s), money=c=>'¥'+(c/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',2800)}
function save(){try{localStorage.setItem('roommate-v1',JSON.stringify(state))}catch{toast('浏览器存储不可用，刷新后本次操作可能丢失')}render()}
function shares(b){if(b.splitSnapshot)return b.splitSnapshot.allocations;const base=Math.floor(b.amount/b.members.length),rest=b.amount%b.members.length;return Object.fromEntries(b.members.map((p,i)=>[p,base+(i<rest?1:0)]))}
function debt(b,p){return p===b.payer||b.paid.includes(p)?0:(shares(b)[p]||0)}
function heading(title,sub,action,label){return `<div class="heading"><div><h1>${title}</h1><p>${sub}</p></div>${action?`<button class="primary" data-add="${action}">＋ ${label}</button>`:`<span class="date-label">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span>`}</div>`}
function billRow(b){return `<div class="row"><div class="row-title"><span class="tile">¥</span><div><h3>${esc(b.title)}</h3><p>${esc(residentName(b.payer))}垫付 · ${b.members.length} 人分摊</p></div></div><div class="amount">${money(shares(b)[state.user]||0)}<small>我的分摊 · 总额 ${money(b.amount)}</small><small>待付 ${money(debt(b,state.user))}</small></div></div>`}
function taskRow(t){return `<div class="row"><div class="row-title"><span class="tile">${t.done?'✓':'⌑'}</span><div><h3>${esc(t.title)}</h3><p>${esc(t.person)} · ${esc(t.date)}${t.date<today()&&!t.done?' · 已逾期':''}</p></div></div><button class="${t.done?'secondary':'primary'} mini" data-task="${t.id}">${t.done?'已完成 ↶':'完成打卡'}</button></div>`}
function itemCard(i){return `<article class="card item"><div class="card-head"><span class="tile">▤</span><span class="tag ${i.qty<=i.threshold?'warn':''}">${i.qty<=i.threshold?'需要补货':'库存充足'}</span></div><h2>${esc(i.title)}</h2><p>剩余 <strong>${i.qty}</strong> ${esc(i.unit)} · 提醒线 ${i.threshold} ${esc(i.unit)}</p><div class="progress"><i style="width:${Math.min(100,i.qty/Math.max(i.threshold*3,1)*100)}%"></i></div><div class="right"><button class="secondary" data-use="${i.id}" ${i.qty===0?'disabled':''}>消耗 1 ${esc(i.unit)}</button><button class="secondary" data-restock="${i.id}">补货</button></div></article>`}
function render(){page=location.hash.slice(1)||'home';if(!['home','bills','chores','items','rules'].includes(page))page='home';const nav=[['home','⌂','家的概览'],['bills','¥','费用 AA'],['chores','▦','清洁值日'],['items','▤','公共物品'],['rules','≡','室友公约']];$('#nav').innerHTML=nav.map(([id,icon,title])=>`<a class="${page===id?'active':''}" href="#${id}"><span>${icon}</span>${title}</a>`).join('');$('#crumb').textContent=nav.find(n=>n[0]===page)[2];$('#identity').value=state.user;const due=state.bills.reduce((s,b)=>s+debt(b,state.user),0),low=state.items.filter(i=>i.qty<=i.threshold),pending=state.tasks.filter(t=>!t.done);let html='';
if(page==='home')html=homeDashboardView(due,low);
if(page==='bills')html=financeView();
if(page==='chores')html=choreBoardView();
if(page==='items')html=heading('公共物品','随手记消耗，缺货前提醒。','item','登记物品')+`<div class="items">${state.items.map(itemCard).join('')}</div><p class="note">达到提醒线时会在首页显示补货提醒。提醒在打开应用时可见，不会发送后台通知。</p>`;
if(page==='rules')html=heading('室友公约','把期待说清楚，让相处更舒服。','rule','新增公约')+state.rules.map((r,i)=>`<article class="card agreement"><div class="card-head"><div class="right"><span class="tile">${String(i+1).padStart(2,'0')}</span><h2>${esc(r.title)}</h2></div><button class="text-link" data-edit-rule="${r.id}">编辑</button></div><p>${esc(r.body)}</p><div class="row"><span class="note">${r.signed.length}/4 人已认可 · ${r.signed.map(esc).join('、')||'等待室友确认'}</span><button class="${r.signed.includes(state.user)?'secondary':'primary'} mini" data-sign="${r.id}">${r.signed.includes(state.user)?'已认可 ✓':'我认可'}</button></div></article>`).join('');$('#content').innerHTML=html}
let submitAction;
function modal(title,fields,fn){$('#dialog-title').textContent=title;$('#fields').innerHTML=fields;submitAction=fn;$('#modal').showModal()}
const input=(label,name,type='text',value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required ${extra}></label>`;
const select=(label,name,value=state.user)=>`<label>${label}<select name="${name}">${people.map(p=>`<option ${p===value?'selected':''}>${p}</option>`).join('')}</select></label>`;
function add(kind){if(kind==='bill')openFinanceBill();
if(kind==='task')openChoreEditor();
if(kind==='item')modal('登记公共物品',input('物品名称','title','text','','maxlength="30"')+input('当前数量','qty','number',1,'min="0" max="9999" step="1"')+input('单位（包、瓶、卷等）','unit','text','包','maxlength="8"')+input('少于或等于此数量时提醒','threshold','number',1,'min="0" max="9999" step="1"'),f=>state.items.push({id:Date.now(),title:f.get('title').trim(),qty:Number(f.get('qty')),unit:f.get('unit').trim(),threshold:Number(f.get('threshold'))}));
if(kind==='rule')editRule()}
function editRule(id){const r=state.rules.find(r=>r.id===id);modal(r?'编辑公约':'新增公约',input('公约标题','title','text',r?.title||'','maxlength="60"')+`<label>具体约定<textarea name="body" required maxlength="1000">${esc(r?.body||'')}</textarea></label><p class="note">修改内容后，所有室友需要重新认可。</p>`,f=>{let data={title:f.get('title').trim(),body:f.get('body').trim(),signed:[]};if(r)Object.assign(r,data);else state.rules.push({id:Date.now(),...data})})}
$('#form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if([...f.values()].some(v=>typeof v==='string'&&!v.trim())){toast('请填写有效内容');return}if(submitAction(f)===false)return;$('#modal').close();save();toast('已保存')};$('#close').onclick=$('#cancel').onclick=()=>$('#modal').close();$('#identity').onchange=e=>{state.user=e.target.value;save()};window.onhashchange=()=>{filter='all';render()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.add)add(d.add);if(d.filter){filter=d.filter;render()}if(d.task){let t=state.tasks.find(t=>t.id==d.task);t.done=!t.done;t.status=t.done?'done':'todo';save();toast(t.done?'已完成，辛苦啦！':'已恢复为待完成')}if(d.pay){let bill=state.bills.find(b=>b.id==d.pay);modal('确认付款',`<p>确认已向 ${esc(residentName(bill.payer))} 支付 <strong>${money(debt(bill,state.user))}</strong>？</p>`,()=>{bill.paid.push(state.user)})}if(d.use){let i=state.items.find(i=>i.id==d.use);i.qty=Math.max(0,i.qty-1);save();toast('已记录消耗')}if(d.restock){let i=state.items.find(i=>i.id==d.restock);modal(`补货 · ${i.title}`,input(`本次增加数量（${i.unit}）`,'qty','number',1,'min="1" max="9999" step="1"'),f=>{i.qty+=Number(f.get('qty'))})}if(d.swap){let t=state.tasks.find(t=>t.id==d.swap);modal('调整值日负责人',select('新负责人','person',t.person),f=>{t.person=f.get('person')})}if(d.rotate){let latest=state.tasks.reduce((s,t)=>t.date>s?t.date:s,today());const date=new Date(latest+'T12:00:00');date.setDate(date.getDate()+7);const next=date.toLocaleDateString('sv-SE');let template=[...new Map(state.tasks.map(t=>[t.title,t])).values()];template.forEach((t,i)=>state.tasks.push({...t,id:Date.now()+i,date:next,person:people[(people.indexOf(t.person)+1)%4],done:false}));save();toast('已生成 '+next+' 的轮值安排')}if(d.editRule)editRule(Number(d.editRule));if(d.sign){const r=state.rules.find(r=>r.id==d.sign);if(!r.signed.includes(state.user)){r.signed.push(state.user);save();toast('已记录你的认可')}}});initFinance();initChores();render();
