let choreWeek='';
const choreAreas=['客厅清洁','厨房台面与灶台','卫生间清洁','倒垃圾 & 更换垃圾袋'];
const choreColors={'小夏':'mint','林一':'amber','陈可':'violet','周舟':'blue'};
function choreDate(value){return new Date(value+'T12:00:00')}
function mondayOf(value){const d=choreDate(value),day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toLocaleDateString('sv-SE')}
function addDays(value,n){const d=choreDate(value);d.setDate(d.getDate()+n);return d.toLocaleDateString('sv-SE')}
function weekDates(start){return Array.from({length:7},(_,i)=>addDays(start,i))}
function initChores(){
  state.tasks.forEach(t=>{t.status ||= t.done?'done':'todo';t.area ||= choreAreas.includes(t.title)?t.title:'其他任务'});
  state.choreSettings ||= {mode:'rotate',startPerson:people[0],weekdays:[0,2,4,6]};
  state.choreSwaps ||= [];
  choreWeek ||= mondayOf(today());
}
function choreStatus(t){return t.status||(t.done?'done':'todo')}
function nextChoreId(list){return Math.max(Date.now(),0,...list.map(item=>Number(item.id)||0))+1}
function homeDashboardView(due,low){
  const todayTasks=state.tasks.filter(t=>t.date===today()),pending=todayTasks.filter(t=>choreStatus(t)==='todo'),mine=pending.filter(t=>t.person===state.user),done=todayTasks.filter(t=>choreStatus(t)==='done').length;
  const monthBills=state.bills.filter(b=>(b.month||b.date.slice(0,7))===today().slice(0,7)),publicTotal=monthBills.reduce((sum,b)=>sum+b.amount,0);
  return heading(`早安，${esc(state.user)} ☀`,'先看看今天和我有关的事。')+`<section class="hero home-hero"><div><div class="welcome-label">TODAY AT 302</div><h2>${mine.length?`今天有 ${mine.length} 项值日等你完成`:'今天的值日已经安排妥当'}</h2><p>${mine.length?'完成后点开任务更新状态，室友会同步看到进度。':'可以轻松开始今天的生活。'}</p></div><div class="hero-mark">${String(new Date().getDate()).padStart(2,'0')}<span>今日</span></div></section>
  <div class="home-section-title"><div><span>我的</span><h2>与我有关</h2></div></div><div class="stats personal-stats"><div class="stat"><label>我的待结清</label><strong>${money(due)}</strong><small><a href="#bills">查看账单明细 →</a></small></div><div class="stat"><label>我的今日值日</label><strong>${mine.length} <small>项</small></strong><small><a href="#chores">查看我的安排 →</a></small></div></div>
  <section class="card today-chores"><div class="card-head"><div><span class="section-kicker">今日待完成</span><h2>我的值日</h2></div><a class="text-link" href="#chores">查看排班 →</a></div>${mine.map(taskRow).join('')||'<p class="empty">今天没有待完成的值日。</p>'}</section>
  <div class="home-section-title public-title"><div><span>全屋</span><h2>302 公共数据</h2></div></div><div class="stats public-stats"><div class="stat"><label>本月公共支出</label><strong>${money(publicTotal)}</strong><small>${monthBills.length} 笔公共账单</small></div><div class="stat"><label>今日值日进度</label><strong>${done} / ${todayTasks.length}</strong><small>还有 ${pending.length} 项待完成</small></div><div class="stat"><label>待补货物品</label><strong>${low.length} <small>种</small></strong><small>全屋共同维护</small></div></div>
  <div class="grid"><section class="card"><div class="card-head"><h2>今日全屋值日</h2><a class="text-link" href="#chores">值日表 →</a></div>${pending.map(taskRow).join('')||'<p class="empty">今日值日全部完成。</p>'}</section><section class="card"><div class="card-head"><h2>补货提醒</h2><a class="text-link" href="#items">管理物品 →</a></div>${low.map(i=>`<div class="row"><div class="row-title"><span class="tile">▤</span><div><h3>${esc(i.title)}</h3><p>仅剩 ${i.qty} ${esc(i.unit)}</p></div></div><button class="secondary mini" data-restock="${i.id}">登记补货</button></div>`).join('')||'<p class="empty">物品充足，安心生活。</p>'}</section></div>`;
}
function choreBoardView(){
  const days=weekDates(choreWeek),weekTasks=state.tasks.filter(t=>days.includes(t.date));
  const done=weekTasks.filter(t=>choreStatus(t)==='done').length,mine=weekTasks.filter(t=>t.person===state.user&&choreStatus(t)!=='done').length;
  return `<div class="chore-heading"><div><h1>清洁值日</h1><div class="chore-stats"><span><strong>${done}</strong> / ${weekTasks.length} 已完成</span><span><strong>${mine}</strong> 项轮到我</span></div></div><div class="chore-actions"><button class="secondary" data-chore-rule="1">轮换规则</button><button class="primary" data-chore-auto="1">一键排班</button></div></div>${swapRequestView()}
  <section class="chore-board card"><div class="board-toolbar"><div class="right"><button class="secondary" data-chore-week="-7" aria-label="上一周">‹</button><button class="secondary current-week" data-chore-today="1">本周</button><button class="secondary" data-chore-week="7" aria-label="下一周">›</button></div><strong>${choreDate(choreWeek).toLocaleDateString('zh-CN',{month:'long',day:'numeric'})} — ${choreDate(addDays(choreWeek,6)).toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</strong><button class="secondary" data-add="task">＋ 单独安排</button></div>
  <div class="chore-scroll"><div class="chore-calendar" style="--chore-days:7"><div class="corner-cell"><span>公共区域</span></div>${days.map(d=>{const dt=choreDate(d),isToday=d===today();return `<div class="day-head ${isToday?'today':''}"><span>周${'日一二三四五六'[dt.getDay()]}</span><strong>${dt.getDate()}</strong>${isToday?'<i>今天</i>':''}</div>`}).join('')}${choreAreas.map(area=>`<div class="area-head"><span class="area-icon">${{'客厅清洁':'⌂','厨房台面与灶台':'♨','卫生间清洁':'≈','倒垃圾 & 更换垃圾袋':'♻'}[area]}</span><strong>${area.replace(' & 更换垃圾袋','')}</strong></div>${days.map(date=>{const tasks=weekTasks.filter(t=>t.area===area&&t.date===date);return `<div class="chore-cell ${date===today()?'today':''}">${tasks.map(choreCard).join('')}<button class="cell-add" data-chore-new="1" data-area="${esc(area)}" data-date="${date}" aria-label="安排${esc(area)}">＋</button></div>`}).join('')}`).join('')}</div></div>
  <div class="board-legend">${people.map(p=>`<span><i class="${choreColors[p]}"></i>${p}</span>`).join('')}<span class="legend-done">✓ 已完成</span></div></section>`;
}
function choreCard(t){const status=choreStatus(t);return `<div class="chore-card ${choreColors[t.person]||'mint'} ${status}"><button data-chore-open="${t.id}"><span>${esc(t.person)}</span><strong>${status==='done'?'已完成':status==='skipped'?'已跳过':'待完成'}</strong>${status==='done'?'<i>✓</i>':''}</button>${status==='todo'?`<button class="swap-link" data-chore-swap="${t.id}">申请调班</button>`:''}</div>`}
function swapRequestView(){const requests=state.choreSwaps.filter(r=>r.status==='pending');if(!requests.length)return '';return `<section class="swap-requests card"><div><strong>调班申请</strong><span>${requests.length} 条待处理</span></div>${requests.map(r=>`<div class="swap-request"><span>${esc(r.from)} 想把 ${monthText(r.date.slice(0,7))}${Number(r.date.slice(8))} 日的${esc(r.area)}换给 ${esc(r.to)}</span>${r.to===state.user?`<button class="secondary mini" data-swap-answer="${r.id}" data-answer="accepted">同意</button><button class="text-link" data-swap-answer="${r.id}" data-answer="rejected">拒绝</button>`:'<small>等待回应</small>'}</div>`).join('')}</section>`}
function openChoreEditor(id,area='',date=''){
  const task=state.tasks.find(t=>t.id===Number(id));
  modal(task?'编辑值日':'安排值日',`<label>区域<select name="area">${choreAreas.map(a=>`<option ${a===(task?.area||area)?'selected':''}>${a}</option>`).join('')}</select></label>${select('负责人','person',task?.person||state.user)}${input('日期','date','date',task?.date||date||today())}<label>状态<select name="status"><option value="todo" ${choreStatus(task||{})==='todo'?'selected':''}>待完成</option><option value="done" ${choreStatus(task||{})==='done'?'selected':''}>已完成</option><option value="skipped" ${choreStatus(task||{})==='skipped'?'selected':''}>跳过</option></select></label>`,f=>{
    const next={area:f.get('area'),title:f.get('area'),person:f.get('person'),date:f.get('date'),status:f.get('status'),done:f.get('status')==='done'};
    if(task)Object.assign(task,next);else state.tasks.push({id:nextChoreId(state.tasks),...next});
    choreWeek=mondayOf(f.get('date'));
  });
}
function copyChoreWeek(){
  const next=addDays(choreWeek,7),current=state.tasks.filter(t=>weekDates(choreWeek).includes(t.date));
  if(!current.length){toast('本周还没有排班');return}
  current.forEach(t=>{const date=addDays(t.date,7);if(!state.tasks.some(x=>x.area===t.area&&x.date===date))state.tasks.push({...t,id:nextChoreId(state.tasks),date,person:people[(people.indexOf(t.person)+1)%people.length],status:'todo',done:false})});
  choreWeek=next;save();toast('下周已排好');
}
function openRotationRule(){const s=state.choreSettings;modal('轮换规则',`<label>轮换方式<select name="mode"><option value="rotate" ${s.mode==='rotate'?'selected':''}>按室友顺序轮换</option><option value="fixed" ${s.mode==='fixed'?'selected':''}>每人固定区域</option></select></label>${select('本周从谁开始','startPerson',s.startPerson)}<div class="rule-preview">${choreAreas.map((a,i)=>`<span>${a.replace(' & 更换垃圾袋','')} · 周${'一二三四五六日'[s.weekdays[i]]}</span>`).join('')}</div>`,f=>{state.choreSettings.mode=f.get('mode');state.choreSettings.startPerson=f.get('startPerson')})}
function autoScheduleWeek(){const s=state.choreSettings,start=people.indexOf(s.startPerson),weekIndex=Math.round((choreDate(choreWeek)-choreDate(mondayOf(today())))/604800000);choreAreas.forEach((area,i)=>{const date=addDays(choreWeek,s.weekdays[i]);if(state.tasks.some(t=>t.area===area&&weekDates(choreWeek).includes(t.date)))return;const offset=s.mode==='fixed'?i:i+weekIndex;state.tasks.push({id:nextChoreId(state.tasks),area,title:area,date,person:people[(start+offset+people.length*100)%people.length],status:'todo',done:false})});save();toast('本周值日已排好')}
function requestChoreSwap(id){const task=state.tasks.find(t=>t.id===Number(id));if(!task)return;modal('申请调班',select('希望换给','to',people.find(p=>p!==task.person)||state.user)+input('原因','reason','text','','maxlength="60"'),f=>{const to=f.get('to');if(to===task.person){toast('请选择另一位室友');return false}state.choreSwaps.push({id:nextChoreId(state.choreSwaps),taskId:task.id,from:task.person,to,area:task.area,date:task.date,reason:f.get('reason').trim(),status:'pending'})},'发送申请')}
function answerSwap(id,answer){const request=state.choreSwaps.find(r=>r.id===Number(id));if(!request||request.to!==state.user)return;request.status=answer;if(answer==='accepted'){const task=state.tasks.find(t=>t.id===request.taskId);if(task)task.person=request.to}save();toast(answer==='accepted'?'已接受调班':'已拒绝调班')}
document.addEventListener('click',e=>{const d=e.target.closest('button')?.dataset;if(!d)return;if(d.choreWeek){choreWeek=addDays(choreWeek,Number(d.choreWeek));render()}if(d.choreToday){choreWeek=mondayOf(today());render()}if(d.choreNew)openChoreEditor(null,d.area,d.date);if(d.choreOpen)openChoreEditor(d.choreOpen);if(d.choreCopy)copyChoreWeek();if(d.choreRule)openRotationRule();if(d.choreAuto)autoScheduleWeek();if(d.choreSwap)requestChoreSwap(d.choreSwap);if(d.swapAnswer)answerSwap(d.swapAnswer,d.answer)});
