const fixedTypes = {rent:'房租',electricity:'电费',water:'水费',gas:'燃气费',internet:'网费',combined:'水电燃气合并账单',other:'其他固定费用'};
let financeMonth='',historyType='',historyMonth='',historyDemo=false;
const archivedMonth=m=>m<today().slice(0,7);
function splitAmount(amount,members){const base=Math.floor(amount/members.length),rest=amount%members.length;return Object.fromEntries(members.map((id,i)=>[id,base+(i<rest?1:0)]))}
function sealBill(b){
  // App-level immutable accounting record. Payment confirmations stay separate from charge allocations.
  if(Object.isFrozen(b))return b;
  b.splitSnapshot ||= {amount:b.amount,members:[...b.members],allocations:splitAmount(b.amount,b.members)};
  Object.freeze(b.splitSnapshot.members);Object.freeze(b.splitSnapshot.allocations);Object.freeze(b.splitSnapshot);
  Object.freeze(b.members);return Object.freeze(b);
}
function occupancyLocked(month){return archivedMonth(month)||state.bills.some(b=>billMonth(b)===month)}
function sealOccupancy(){for(const [month,ids] of Object.entries(state.finance.occupancy)){if(occupancyLocked(month)){Object.freeze(ids);Object.defineProperty(state.finance.occupancy,month,{value:ids,writable:false,configurable:false,enumerable:true})}}}
function myTotal(bs){return bs.reduce((sum,b)=>sum+(shares(b)[state.user]||0),0)}
function splitExplanation(b){const mine=shares(b)[state.user];if(mine===undefined)return '我未参与此笔分摊';const snapshot=b.splitSnapshot||b;return `${money(snapshot.amount)} ÷ ${snapshot.members.length} 人 = ${money(mine)}${snapshot.amount%snapshot.members.length?'（余分按参与顺序分配）':''}`}
function updateSplitPreview(){
  const panel=document.querySelector('#split-preview');if(!panel)return;
  const amount=Math.round(Number(document.querySelector('#fields input[name="amount"]').value)*100);
  const members=[...document.querySelectorAll('#fields input[name="members"]:checked')].map(el=>el.value);
  if(!amount||!members.length){panel.textContent='输入总额并选择参与者后，自动预览每人分摊。';return}
  const allocations=splitAmount(amount,members);
  panel.innerHTML=`<strong>总额 ${money(amount)} · ${members.length} 人均摊</strong><p>我的账单：${Object.hasOwn(allocations,state.user)?`${money(amount)} ÷ ${members.length} = ${money(allocations[state.user])}`:'¥0.00（未参与）'}</p><div>${members.map(id=>`<span>${esc(id)} ${money(allocations[id])}</span>`).join('')}</div>${amount%members.length?'<small>不足整分的余数，按参与顺序逐人分配，确保合计等于总额。</small>':''}`;
}
function residentName(id){return people.includes(id)?id:'已退租室友'}
function classifyBill(b){
  if(b.category)return;
  if(/水电|水.*燃气|电.*燃气/.test(b.title)){b.category='fixed';b.type='combined'}
  else {const found=[['rent',/房租/],['electricity',/电费/],['water',/水费/],['gas',/燃气|煤气/],['internet',/网费|宽带/]].find(([,re])=>re.test(b.title));b.category=found?'fixed':'personal';b.type=found?.[0]||'personal'}
}
function initFinance(){
  state.finance ||= {occupancy:{}};
  state.finance.occupancy ||= {};
  state.bills.forEach(b=>{classifyBill(b);b.month ||= b.date.slice(0,7)});
  // The current household is known; past occupants are never inferred from a bill's split participants.
  state.finance.occupancy[today().slice(0,7)] ||= [...people];
  state.bills.forEach(sealBill);sealOccupancy();
  financeMonth ||= today().slice(0,7);
  try{localStorage.setItem('roommate-v1',JSON.stringify(state))}catch{}
}
function monthText(m){return m.replace('-',' 年 ')+' 月'}
function shiftMonth(m,n){const [y,mo]=m.split('-').map(Number);const d=new Date(y,mo-1+n,1,12);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function billMonth(b){return b.month||b.date.slice(0,7)}
function sumBills(bs){return bs.reduce((s,b)=>s+b.amount,0)}
function occupantChips(ids){return ids.map(id=>people.includes(id)?`<span class="occupant"><b>${esc(id.slice(0,1))}</b><span>${esc(id)}</span></span>`:`<span class="occupant departed" aria-label="已退租室友"><b aria-hidden="true"><svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor"><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3z"/></svg></b></span>`).join('')}
function financeView(){
  const bs=state.bills.filter(b=>billMonth(b)===financeMonth),fixed=bs.filter(b=>b.category==='fixed'),personal=bs.filter(b=>b.category==='personal');
  const due=bs.reduce((s,b)=>s+debt(b,state.user),0);
  return heading('费用 AA','固定开销按月看，个人花费分开记。','bill','记一笔')+`
    <div class="finance-month"><div class="right"><button class="secondary" data-month-step="-1" aria-label="上个月">‹</button><label><span class="sr-only">账单月份</span><input type="month" id="finance-month" value="${financeMonth}" min="2000-01" max="2100-12"></label><button class="secondary" data-month-step="1" aria-label="下个月">›</button></div><span class="tag">${archivedMonth(financeMonth)?"历史月份已归档 · 只读":"记录后锁定金额与分摊人"}</span></div>
    <div class="finance-summary"><div><span>所选月份 · 全屋总费用</span><strong>${money(sumBills(bs))}</strong><small>固定 ${money(sumBills(fixed))} · 其他 ${money(sumBills(personal))}</small></div><div><span>我的账单 · 个人应分摊</span><strong>${money(myTotal(bs))}</strong><small>逐笔按参与人数计算，与付款状态无关</small></div><div><span>我的待付款</span><strong class="success">${money(due)}</strong><small>已付款或我已垫付的费用不再待付</small></div></div>
    <div class="expense-columns"><section class="card"><div class="card-head"><div><h2>固定居住费用</h2><p class="note">房租、水电燃气、网络等必要开销</p></div><span class="tag">按月归档</span></div>
    <div class="fixed-list">${Object.entries(fixedTypes).filter(([key])=>!['combined','other'].includes(key)||state.bills.some(b=>b.type===key)).map(([key,title])=>{const list=fixed.filter(b=>b.type===key);return `<button class="fixed-expense" data-history="${key}"><span class="row-title"><span class="tile">${{rent:'⌂',electricity:'ϟ',water:'≈',gas:'♨',internet:'⌁'}[key]||'≡'}</span><span><strong>${title}</strong><small>${list.length?list.length+' 笔账单':'本月未记录'}</small></span></span><span class="expense-total"><strong>我的 ${list.length?money(myTotal(list)):'—'}</strong><small>全屋总额 ${list.length?money(sumBills(list)):'—'}</small><small>查看分摊与历史 →</small></span></button>`}).join('')}</div></section>
    <section class="card personal-panel"><div class="card-head"><div><h2>其他个人费用</h2><p class="note">聚餐、代买、日用品，仅参与者分摊</p></div><button class="text-link" data-personal-add="1">＋ 记一笔</button></div>${personal.length?personal.map(b=>`<div class="personal-expense"><div class="row"><div><h3>${esc(b.title)}</h3><p>${esc(residentName(b.payer))}垫付 · ${b.members.length} 人参与</p></div><span class="amount">${money(shares(b)[state.user]||0)}<small>我的分摊 · 总额 ${money(b.amount)}</small></span></div><div class="personal-bottom"><span>${splitExplanation(b)}</span>${paymentButton(b)}</div></div>`).join(''):'<div class="finance-empty"><span>＋</span><h3>本月还没有其他费用</h3><p>一起吃饭或帮忙代买后，随手记一笔。</p><button class="secondary" data-personal-add="1">记录个人费用</button></div>'}</section></div>
    <section class="card finance-ledger"><div class="card-head"><h2>我的账单明细</h2><div class="toolbar"><button data-filter="all" class="${filter==='all'?'selected':''}">全部</button><button data-filter="due" class="${filter==='due'?'selected':''}">我待结清</button></div></div>${financeTable(bs.filter(b=>filter!=='due'||debt(b,state.user)>0))}<p class="note">金额与参与人按记账时的记录计算，不随室友退租或付款状态改变。历史月份不可新增账单或修改入住记录；付款确认只更新结清状态。</p></section>`;
}
function paymentButton(b){return debt(b,state.user)>0?`<button class="primary mini" data-pay="${b.id}">标记已付款</button>`:`<span class="tag">${b.payer===state.user?'我已垫付':b.members.includes(state.user)?'已结清':'未参与'}</span>`}
function financeTable(bs,readOnly=false){return bs.length?`<div class="table-wrap"><table><thead><tr><th>费用项目</th><th>总金额</th><th>垫付人</th><th>我的账单 / 计算依据</th>${readOnly?'':'<th>状态</th>'}</tr></thead><tbody>${bs.map(b=>`<tr><td><strong>${esc(b.title)}</strong><p class="note">${esc(b.date)} · ${b.category==='fixed'?'固定居住':'其他个人'}费用</p></td><td>${money(b.amount)}</td><td>${people.includes(b.payer)?esc(b.payer):occupantChips([b.payer])}</td><td><strong class="success">${money(shares(b)[state.user]||0)}</strong><p class="note">${splitExplanation(b)}</p></td>${readOnly?'':`<td>${paymentButton(b)}</td>`}</tr>`).join('')}</tbody></table></div>`:'<p class="empty">该月暂无符合条件的账单</p>'}
function historySamples(type){const now=today().slice(0,7),amounts=type==='rent'?[480000,480000,480000,480000,480000,480000]:type==='electricity'?[12640,15860,22480,31820,28640,19680]:type==='water'?[6800,7200,7600,8500,8100,7400]:type==='gas'?[4600,5200,3800,4100,4400,4900]:type==='internet'?[10000,10000,10000,10000,10000,10000]:[18000,21000,26000,33000,29000,24000];return amounts.map((amount,i)=>({id:'demo-'+i,category:'fixed',type,amount,month:shiftMonth(now,i-5),date:shiftMonth(now,i-5)+'-05',title:fixedTypes[type]+'（示例）',payer:'林一',members:i<3?['小夏','林一','陈可','anonymous-1']:[...people],paid:[...people]}))}
function monthlyHistory(type,records){const actual=records.filter(b=>b.category==='fixed'&&b.type===type);const anchor=historyMonth||financeMonth;const end=actual.reduce((v,b)=>billMonth(b)>v?billMonth(b):v,anchor);const earliest=actual.reduce((v,b)=>billMonth(b)<v?billMonth(b):v,shiftMonth(end,-5));let result=[];for(let m=earliest;m<=end;m=shiftMonth(m,1)){const bills=actual.filter(b=>billMonth(b)===m);result.push({month:m,total:sumBills(bills),recorded:!!bills.length,bills})}return result}
function showHistory(type){historyType=type;historyMonth=financeMonth;historyDemo=false;const d=document.createElement('dialog');d.id='expense-history';d.className='history-dialog';d.setAttribute('aria-label',fixedTypes[type]+'历史');document.body.appendChild(d);d.addEventListener('close',()=>d.remove());drawHistory();d.showModal()}
function drawHistory(){const target=$('#expense-history');if(!target)return;const records=historyDemo?historySamples(historyType):state.bills;const months=monthlyHistory(historyType,records),selected=months.find(m=>m.month===historyMonth)||months.at(-1);historyMonth=selected.month;const max=Math.max(...months.map(m=>m.total),1),recorded=months.filter(m=>m.recorded);const previous=months.find(m=>m.month===shiftMonth(selected.month,-1));const pct=previous?.recorded&&previous.total>0&&selected.recorded?((selected.total-previous.total)/previous.total*100):null;const occupants=historyDemo?(selected.bills[0]?.members):state.finance.occupancy[historyMonth];
target.innerHTML=`<div class="dialog-head"><div><span class="history-eyebrow">302 · 固定居住费用</span><h2>${fixedTypes[historyType]}历史</h2></div><button class="icon" data-history-close="1" aria-label="关闭历史">×</button></div><div class="history-switch"><button class="${!historyDemo?'selected':''}" data-history-source="actual">实际记录</button><button class="${historyDemo?'selected':''}" data-history-source="demo">查看示例走势</button></div>${historyDemo?'<div class="demo-notice">示例数据 · 仅演示月度走势和退租头像，不计入你的账单。</div>':''}<div class="history-chart-head"><div><h3>每月总${fixedTypes[historyType]}</h3><p class="note">图表展示全屋总额；点选月份，在下方查看我的分摊。</p></div><span class="tag">${recorded.length} 个月有记录</span></div><div class="chart-scroll"><div class="month-chart" style="--months:${months.length}">${months.map(m=>`<button class="chart-column ${m.month===historyMonth?'selected':''}" data-history-month="${m.month}" aria-pressed="${m.month===historyMonth}" aria-label="${monthText(m.month)}，${m.recorded?money(m.total):'未记录'}"><span class="bar-space"><span class="bar" style="height:${m.recorded?Math.max(2,m.total/max*100):0}%"><span class="bar-label">${m.recorded?money(m.total):'未记录'}</span></span>${!m.recorded?'<span class="unrecorded-line"></span>':''}</span><span class="month-tick">${m.month.slice(0,4)}<br><strong>${Number(m.month.slice(5))} 月</strong></span></button>`).join('')}</div></div><p class="note chart-key">单位：元 · 未记录的月份不按 0 元计算</p><section class="history-detail"><div class="card-head"><div><h3>${monthText(historyMonth)}</h3><p class="note">${selected.bills.length} 笔账单</p></div><div class="amount"><small>全屋总费用</small>${selected.recorded?money(selected.total):'尚未记录'}<small>${pct===null?'暂无可比较的上月记录':`较上月${pct>0?'增加':pct<0?'减少':'持平'}${pct===0?'':' '+Math.abs(pct).toFixed(1)+'%'}`}</small></div></div><div class="my-share-detail"><div><span>我的账单 · ${esc(state.user)}</span><strong>${selected.recorded?money(myTotal(selected.bills)):'—'}</strong></div><p>${selected.bills.length===1?splitExplanation(selected.bills[0]):selected.bills.length?'逐笔计算个人分摊后相加，详见下方明细':'本月没有费用记录'}</p></div><div class="occupancy-head"><h3>当月入住人${occupants?' · '+occupants.length+' 人':''}</h3>${historyDemo?'<span class="tag">示例 · 只读</span>':occupancyLocked(historyMonth)?'<span class="tag">入住记录已锁定</span>':'<button class="text-link" data-occupancy-edit="1">登记入住记录</button>'}</div><div class="occupants">${occupants?occupantChips(occupants):'<p class="note">此月未留存入住记录，不推测或改写历史。</p>'}</div><p class="note">仍住在 302 的室友显示名字；已退租的室友仅显示灰色头像。</p></section><div class="history-bills"><h3>我的当月分摊明细</h3>${financeTable(selected.bills,true)}</div>`;
}
function openFinanceBill(personal=false){
const entryMonth=archivedMonth(financeMonth)?today().slice(0,7):financeMonth;
modal('记一笔费用',`<label>费用归类<select name="category" id="bill-category"><option value="fixed" ${personal?'':'selected'}>固定居住费用</option><option value="personal" ${personal?'selected':''}>其他个人费用</option></select></label><label id="bill-type-label" ${personal?'hidden':''}>费用项目<select name="type">${Object.entries(fixedTypes).filter(([k])=>k!=='combined').map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label>`+input('支出说明','title','text','','maxlength="50"')+input('金额（元）','amount','number','','min="0.01" max="1000000" step="0.01"')+input('费用所属月份（历史月份已锁定）','month','month',entryMonth,`min="${today().slice(0,7)}" max="2100-12"`)+select('谁先垫付','payer')+input('付款日期','date','date',today())+`<p class="note">保存后锁定总额和分摊人，请先确认。已归档的历史月份不可补记或覆盖。</p><label>参与均摊的室友（仅勾选参与者）</label><div class="checks">${people.map(p=>`<label><input type="checkbox" name="members" value="${p}" ${!personal||p===state.user?'checked':''}>${p}</label>`).join('')}</div><div id="split-preview" class="split-preview" aria-live="polite"></div>`,f=>{if(archivedMonth(f.get('month'))){toast('历史月份已归档，不能新增或改写账单');return false}const members=f.getAll('members');if(!members.length){toast('请至少选择一位分摊室友');return false}const amount=Math.round(Number(f.get('amount'))*100);if(!Number.isSafeInteger(amount)||amount<=0){toast('请输入有效金额');return false}const category=f.get('category');state.bills.push(sealBill({id:Date.now(),title:f.get('title').trim(),amount,payer:f.get('payer'),members,date:f.get('date'),month:f.get('month'),category,type:category==='fixed'?f.get('type'):'personal',paid:[],recordedAt:new Date().toISOString()}));sealOccupancy();financeMonth=f.get('month')});
updateSplitPreview();
}
function editOccupancy(){if(historyDemo||occupancyLocked(historyMonth)){toast('入住记录已锁定，不能修改');return}const editMonth=historyMonth;const ids=state.finance.occupancy[historyMonth]||[];modal(monthText(historyMonth)+'入住记录',`<p class="note">选择当月实际入住、现在仍住在 302 的室友。退租室友仅登记人数，不录入姓名。</p><div class="checks">${people.map(p=>`<label><input type="checkbox" name="occupants" value="${p}" ${ids.includes(p)?'checked':''}>${p}</label>`).join('')}</div>`+input('当月入住、现已退租的人数','departed','number',ids.filter(p=>!people.includes(p)).length,'min="0" max="20" step="1"'),f=>{if(occupancyLocked(editMonth)){toast('入住记录已锁定，不能修改');return false}const count=Number(f.get('departed'));state.finance.occupancy[editMonth]=[...f.getAll('occupants'),...Array.from({length:count},(_,i)=>'anonymous-'+i)];drawHistory()})}
document.addEventListener('change',e=>{if(e.target.id==='finance-month'&&e.target.validity.valid&&e.target.value){financeMonth=e.target.value;render()}if(e.target.id==='bill-category'){document.querySelector('#bill-type-label').hidden=e.target.value==='personal';document.querySelectorAll('#fields input[name="members"]').forEach(el=>{el.checked=e.target.value==='fixed'||el.value===state.user})}if(['amount','members','category'].includes(e.target.name))updateSplitPreview()});
document.addEventListener('input',e=>{if(e.target.name==='amount')updateSplitPreview()});
document.addEventListener('click',e=>{const d=e.target.closest('button')?.dataset;if(!d)return;if(d.monthStep){financeMonth=shiftMonth(financeMonth,Number(d.monthStep));render()}if(d.personalAdd)openFinanceBill(true);if(d.history)showHistory(d.history);if(d.historyClose)$('#expense-history').close();if(d.historyMonth){historyMonth=d.historyMonth;drawHistory()}if(d.historySource){historyDemo=d.historySource==='demo';historyMonth=historyDemo?today().slice(0,7):financeMonth;drawHistory()}if(d.occupancyEdit)editOccupancy()});
