const fs=require('fs'),vm=require('vm'),assert=require('assert');
const nodes={},listeners={};
const node=()=>({innerHTML:'',textContent:'',value:'',style:{},showModal(){},close(){},remove(){},setAttribute(){},addEventListener(){}});
const context={console,Date,Map,Number,String,Object,Math,JSON,location:{hash:'#chores'},localStorage:{getItem:()=>null,setItem:()=>{}},document:{querySelector:s=>nodes[s]??=node(),querySelectorAll:()=>[],createElement:node,body:{appendChild(){}},addEventListener:(event,fn)=>(listeners[event]??=[]).push(fn)},window:{},setTimeout:()=>0,clearTimeout(){}};
vm.createContext(context);
for(const file of ['finance.js','chores.js','app.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context);
vm.runInContext(`
assert=(condition,message)=>{if(!condition)throw Error(message)};
assert(mondayOf('2026-09-13')==='2026-09-07','week starts Monday');
assert(weekDates('2026-09-07').length===7,'seven days');
assert(choreAreas.length===4,'four household areas');
const html=choreBoardView();
assert((html.match(/class="day-head/g)||[]).length===7,'seven date headers');
assert((html.match(/class="chore-cell/g)||[]).length===28,'complete weekly grid');
assert(html.includes('一键排班')&&html.includes('轮换规则')&&html.includes('轮到我'),'board controls and personal count');
const home=homeDashboardView(0,[]);
assert(home.includes('MY DAY')&&home.includes('全屋动态'),'home separates personal and household data');
assert((home.match(/<section/g)||[]).length===2,'home uses two consolidated panels');
assert(home.includes('待付款')&&home.includes('待收款'),'personal card focuses on money alongside the check-in task');
assert(homeGreeting(8).title==='早安'&&homeGreeting(10).title==='上午好'&&homeGreeting(12).title==='中午好'&&homeGreeting(16).title==='下午好'&&homeGreeting(20).title==='晚上好'&&homeGreeting(23).title==='晚安','greeting follows time of day');
const before=state.tasks.length;openChoreEditor(null,'客厅清洁',today());
submitAction({get:key=>({area:'客厅清洁',person:'周舟',date:today(),status:'todo'})[key]});
assert(state.tasks.length===before+1&&state.tasks.at(-1).area==='客厅清洁','assign from cell');
const task=state.tasks.at(-1);openChoreEditor(task.id);submitAction({get:key=>({area:'客厅清洁',person:'周舟',date:today(),status:'done'})[key]});
assert(task.done&&task.status==='done','edit card status');
const currentStart=choreWeek,beforeCopy=state.tasks.length;copyChoreWeek();
assert(choreWeek===addDays(currentStart,7),'advance to next week');
assert(state.tasks.length>beforeCopy,'copy next week assignments');
assert(state.tasks.slice(beforeCopy).every(t=>t.status==='todo'&&!t.done),'copied tasks reset status');
choreWeek=addDays(currentStart,21);const beforeAuto=state.tasks.length,historyBefore=JSON.stringify(state.tasks.filter(t=>t.date<choreWeek));autoScheduleWeek();
assert(state.tasks.length===beforeAuto+28,'one-click schedule fills seven days and four areas');
assert(weekDates(choreWeek).every(date=>choreAreas.every(area=>state.tasks.some(t=>t.date===date&&t.area===area))),'every weekly cell is scheduled');
assert(JSON.stringify(state.tasks.filter(t=>t.date<choreWeek))===historyBefore,'one-click schedule preserves history');
const swapTask=state.tasks.at(-1),swapTo=people.find(p=>p!==swapTask.person);requestChoreSwap(swapTask.id);submitAction({get:key=>({to:swapTo,reason:'临时有事'})[key]});
assert(swapTo!==swapTask.person,'swap target differs from current assignee');
assert(state.choreSwaps.at(-1).status==='pending','create swap request');
state.user=swapTo;
answerSwap(state.choreSwaps.at(-1).id,'accepted');
assert(swapTask.person===state.user&&state.choreSwaps.at(-1).status==='accepted','accept swap updates assignee');
console.log('PASS: weekly board, one-click scheduling, rotation, swap request, and home data grouping');
`,context);
